[project]
name = "dltworkshop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dlt[duckdb]>=1.29.0",
    "dotenv>=0.9.9",
    "fastmcp-slim[server]>=3.4.4",
    "logfire>=4.37.0",
    "minsearch>=0.2.0",
    "openai>=2.46.0",
    "pydantic-ai>=2.13.0",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
]
